<?php
/**
 * Changes the field length for gallery image captions
 */
function ysom_cases_update_7001() {

 if(  field_info_field('field_image_caption') ){
  // Alter columns length
  db_query("ALTER TABLE field_data_field_image_caption CHANGE COLUMN field_image_caption_value field_image_caption_value VARCHAR(255) NULL DEFAULT NULL");
  db_query("ALTER TABLE field_revision_field_image_caption CHANGE COLUMN field_image_caption_value field_image_caption_value VARCHAR(255) NULL DEFAULT NULL");
  // Update field config
  $result = db_query("SELECT data FROM field_config WHERE field_name = 'field_image_caption'")->fetchObject();
  $data = unserialize($result->data);
  $data['settings']['max_length'] = "255";
  $qry = "UPDATE field_config SET data = :data WHERE field_name = 'field_image_caption'";
  db_query($qry, array(':data' => serialize($data) ));
 }
}

/**
 * Installs the warpwire_video_node content_type
 */
function ysom_cases_update_7002() {
  module_enable(array('warpwire_video_node_type'));
}

/**
 * Implements hook_node_validate
 *  Make sure the three part date is a valid date
 */
function ysom_cases_node_validate($node, $form, &$form_state) {
  if ($form_state['values']['field_video_year'][LANGUAGE_NONE][0]['value'] ==  '') {
    $form_state['values']['field_video_year'][LANGUAGE_NONE][0]['value'] = null;
  }
  $values = $form_state['values'];
  if (isset($values['field_video_year'][LANGUAGE_NONE][0]['value']) &&
    isset($values['field_video_month'][LANGUAGE_NONE][0]['value']) &&
    isset($values['field_video_day'][LANGUAGE_NONE][0]['value'])) {

    $y = substr($values['field_video_year'][LANGUAGE_NONE][0]['value'] , 0 , 4);
    $m = $values['field_video_month'][LANGUAGE_NONE][0]['value'];
    $d = $values['field_video_day'][LANGUAGE_NONE][0]['value'];

    $entered_date = "$m $d $y";
    $computed_date = date('F j Y' ,strtotime($entered_date));
    if ($entered_date != $computed_date) {
      $msg = "Invalid Video Date entered:  $entered_date";
      form_set_error('field_video_day' , $msg);
    }
  }
}

 /* Implements hook_node_presave
 *  this is needed because the fields dependecy module does not always
 *  resets dependent fields when dependee is not set
 */
function ysom_cases_node_presave($node){
  if ($node->type == 'warpwire_video') {
    $remove = 0;
    $month = $node->field_warpwire_month;
    $day = $node->field_warpwire_day;
    if (array_key_exists('value' , $node->field_video_year[LANGUAGE_NONE][0])) {
      if (!is_string($node->field_video_year[LANGUAGE_NONE][0]['value'])) {
        $remove = 2;
      } else {
        // we have a year and its valid...lets check to see if we have a month
        if (array_key_exists('value' , $node->field_video_month[LANGUAGE_NONE][0])) {
          if (!is_string($node->field_video_month[LANGUAGE_NONE][0]['value'])) {
            $remove = 1;
          }
        } else {
          $remove = 1;
        }
      }
    } else {
        $remove = 2;
    }
    if ($remove) {
      $index_ary = array(
        1 => 'field_video_day',
        2 => 'field_video_month',
      );
      for ($x = 1 ; $x<=$remove ; $x++) {
        $index = $index_ary[$x];
        $node->$index = array();
      }
    }
  }
}
