<?php

function subscribers_menu() {
  $items = array();
  $items['case-subscriber'] = array(
    'page callback' = 'subscriber_check',

  );
  return $items;
}

function subscriber_check() {
  $referrer = $_SERVER['HTTP_REFERER'];
  dpm($referrer);
  if ($referrer == $referrer) {
    $done = FALSE;
    $x = 0;
    $arg_ary = array();
    while (!$done) {
      $arg = arg($x);
      if ($arg) {
        $arg_ary[] = $arg;
        $x++;
      } else {
        $done = TRUE;
      }
    }
    unset($arg_ary[0]) // this is case-subsriber
    $uri = implode('/', $arg_ary);
    drupal_goto($uri);
}
