<?php

/**
 * Implements hook_uninstall().
 */
function warpwire_uninstall() {
	variable_del('warpwire_url');
	variable_del('warpwire_lti_url');
	variable_del('warpwire_group_name');
	variable_del('warpwire_oauth_consumer_key');
	variable_del('warpwire_oauth_secret');
	variable_del('warpwire_share_default');
	variable_del('warpwire_title_default');
	variable_del('warpwire_autoplay_default');
	variable_del('warpwire_cc_load_policy_default');		
}
